#!/usr/bin/env bash

dir=$(cd `dirname $0` && pwd)

echo "alias vpnfix='sudo $dir/vpn-fix $dir/whitelist.txt'" >> ~/.bash_profile

echo "'vpnfix' alias created in ~/.bash_profile. Reopen your terminal window or run 'source ~/.bash_profile' and then run 'vpnfix'"
